version: '2'
services:

  hadoop-master:
    image: 'prestodev/hdp3.1-hive:${DOCKER_IMAGES_VERSION}'
    command: "/docker/presto-product-tests/conf/docker/singlenode-hdp3/hadoop-master/docker-command.sh"

  application-runner:
    environment:
      - TEMPTO_PROFILE_CONFIG_FILE=/docker/presto-product-tests/conf/tempto/tempto-configuration-for-hdp3.yaml
