version: '2'
services:

  java-8-base:
    image: 'prestodev/centos6-oj8:${DOCKER_IMAGES_VERSION}'
    volumes:
      - ../..:/docker/presto-product-tests/conf
      - ../../target:/docker/logs

  hadoop-master:
    extends:
      service: java-8-base
    image: '${HADOOP_BASE_IMAGE}:${DOCKER_IMAGES_VERSION}'
    hostname: hadoop-master
    ports:
      - '${HIVE_PROXY_PORT}:1180'
      - '5006:5006'
      - '8020:8020'
      - '8042:8042'
      - '8088:8088'
      - '9000:9000'
      - '9083:9083' # Metastore Thrift
      - '9864:9864' # DataNode Web UI since Hadoop 3
      - '9870:9870' # NameNode Web UI since Hadoop 3
      - '10000:10000' # HiveServer2
      - '19888:19888'
      - '50070:50070' # NameNode Web UI prior to Hadoop 3
      - '50075:50075' # DataNode Web UI prior to Hadoop 3
    volumes:
      - ../../../src/main/resources/avro:/docker/avro

  presto-master:
    extends:
      service: java-8-base
    image: 'prestodev/centos7-oj11:${DOCKER_IMAGES_VERSION}'
    hostname: presto-master
    command: /docker/presto-product-tests/conf/docker/files/presto-launcher-wrapper.sh singlenode run
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - hadoop-master
    volumes:
      - ${PRESTO_SERVER}:/docker/presto-server.tar.gz
      - ../../../src/main/resources/avro:/docker/avro

  application-runner:
    extends:
      service: java-8-base
    hostname: application-runner
    command: bash -c 'echo please provide command to application-runner >&2; exit 1'
    volumes:
      - ${PRESTO_CLI_JAR}:/docker/presto-cli-executable.jar
      - ${PRODUCT_TESTS_JAR}:/docker/presto-product-tests-executable.jar
      - ${PRESTO_JDBC_DRIVER_JAR_DIR}:/docker/volumes/jdbc/
      - ${PRESTO_JDBC_DRIVER_JAR}:/docker/presto-jdbc.jar
      - ../../../target/test-reports:/docker/test-reports
      - ${PRESTO_CLI_HISTORY_FILE}:/root/.presto_history
    environment:
      - PRESTO_JDBC_DRIVER_CLASS
      - TESTS_HIVE_VERSION_MAJOR
      - TESTS_HIVE_VERSION_MINOR
      - TEMPTO_ENVIRONMENT_CONFIG_FILE
      - TEMPTO_EXTRA_CONFIG_FILE
      - CLI_ARGUMENTS=--server presto-master:8080
