version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka 
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  presto-master:
    volumes:
      - ../../../conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka.properties:/docker/presto-product-tests/conf/presto/etc/catalog/kafka.properties
      - ../../../conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka:/docker/presto-product-tests/conf/presto/etc/catalog/kafka

  application-runner:
    volumes:
      - ../../../conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka:/docker/presto-product-tests/conf/presto/etc/catalog/kafka
